name: Build App CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Refresh Packages
    - run: apt-get update && apt-get upgrade -y
    - name: Install Libraries
    - run: apt-get install qtbase5-dev qt5-qmake build-essential libhdhomerun-dev -y
    - name: Build 
    - run: qmake && make
      
